server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://175.178.79.245:3306/railsystem
    username: railsystem
    password: Fz5M4raeGpDs6P4e